version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5000:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app-network

  service:
    container_name: jatis-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "9000:9000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
    links:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db:
    driver: local
