version: "3.9"

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '30000:5432'
    volumes:
      - db:/var/lib/postgresql/data
  service:
    container_name: jatis-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:9000"
    network_mode: "host"
    depends_on:
      - db
    links:
      - db
